app_buat_berita/urls.py
from django.urls import path
from . import views

app_name = 'app_buat_berita'
urlpatterns = [
    path('', views.buat_berita, name='buat_berita'),
    path('/go-to-profile', views.go_to_profile, name='go_to_profile')
]

app_buat_polling_berita/urls.py
from django.urls import path
from . import views

app_name = 'app_buat_polling_berita'
urlpatterns = [
    path('', views.buat_polling_berita, name='buat_polling_berita')
]

app_buat_polling_biasa/urls.py
from django.urls import path
from . import views

app_name = 'app_buat_polling_biasa'
urlpatterns = [
    path('', views.buat_polling_biasa, name='buat_polling_biasa')
]

app_login/urls.py
from .views import index, login, logout
from django.conf.urls import url

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login', login, name='login'),
    url(r'^logout', logout, name='logout'),
]

bmnc_news/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
import app_login.urls as login
import app_registrasi.urls as registrasi
from django.urls import path, include
from app_polling import views as views_polling


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('app_profile.urls')),
    path('berita/', include('app_berita.urls')),
    path('polling/', views_polling.index),
    path('buat-berita/', include('app_buat_berita.urls', namespace='app_buat_berita')),
    path('buat-polling-berita/', include('app_buat_polling_berita.urls', namespace='app_buat_polling_berita')),
    path('buat-polling-biasa/', include('app_buat_polling_biasa.urls', namespace='app_buat_polling_biasa')),
    url(r'^login/', include(('app_login.urls','login'), namespace='login')),
    url(r'^registrasi/', include(('app_registrasi.urls','registrasi'), namespace='registrasi')),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='index'),
]

app_buat_polling_biasa/models.py
from django.db import models

# Create your models here.

app_buat_polling_biasa/views.py
from django.shortcuts import render
from django.db import connection
from app_database.models import *
from django.db.utils import ProgrammingError
response = {}
# Create your views here.
def buat_polling_biasa(request):
    response['error'] = None
    response['success'] = None
    if (request.method=="POST"):
        id_polling = len(list(Polling.objects.raw("SELECT * FROM POLLING"))) + 1
        waktu_mulai = request.POST['waktu_mulai'] + " 00:00:00"
        waktu_selesai = request.POST['waktu_selesai'] + " 23:59:59"
        total_responded = 0

        deskripsi = request.POST['deskripsi']
        url_polling = 'dummy'

        try:
            with connection.cursor() as cursor:
                command = "INSERT INTO POLLING VALUES ('%d','%s','%s','%d')" % (id_polling,waktu_mulai,waktu_selesai,total_responded)
                cursor.execute(command)
                command = "INSERT INTO POLLING_BIASA VALUES ('%d','%s','%s')" % (id_polling,url_polling,deskripsi)
                cursor.execute(command)
                response['error'] = None
                response['success'] = "Data berhasil disimpan"
        except Exception as e:
            response['error'] = 'Ada yang salah'
            response['success'] = None

    return render(request, 'buat-polling-biasa.html', response)

app_buat_polling_biasa/templates/buat-polling-biasa.html
<!DOCTYPE html>
{% load staticfiles %}
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'css/now-ui-kit.css' %}"> </head>
</head>

<body>
  <nav class="navbar navbar-expand-md bg-primary navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i>
        <b> Biru Merah News Company</b>
      </a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
        <a class="btn btn-primary" href="{% url 'app_buat_berita:buat_berita' %}">Buat Berita</a>
        <a class="btn btn-primary" href="{% url 'app_buat_polling_berita:buat_polling_berita' %}">Buat Polling Berita</a>
        <a class="btn btn-primary" href="{% url 'app_buat_polling_biasa:buat_polling_biasa' %}">Buat Polling Biasa</a>
        <a class="btn btn-primary" href="{% url 'app_buat_berita:go_to_profile' %}">Profile</a>
        <a class="btn btn-primary" href="{% url 'login:logout' %}">Log Out</a>
      </div>
    </div>
  </nav>
  <div class="py-3">
    <div class="container">
      {% if error %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ error }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      {% if success %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ success }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-12"></div>
          </div>
          <h1 class="">Polling Biasa</h1>
        </div>
      </div>
    </div>
  </div>
  <div class="">
    <div class="container">
      <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
          <form class="" method="POST" action="{% url 'app_buat_polling_biasa:buat_polling_biasa' %}">
            {% csrf_token %}
            <div class="form-group">
              <label>Deskripsi</label>
              <input type="text" class="form-control" name="deskripsi" placeholder="Masukan Deskripsi" required> </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>Waktu Mulai</label>
                  <input type="date" class="form-control" name="waktu_mulai" placeholder="Maukan Url" required> </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>Waktu Selesai</label>
                  <input type="date" class="form-control" name="waktu_selesai" placeholder="Maukan Url" required> </div>
              </div>
            </div>
            <div id="pertanyaan">
            <div class="form-group">
              <label>Pertanyaan Seputar Polling</label>
              <input type="text" class="form-control" placeholder="Maukan Pertanyaan"> </div>
            </div>
            <div class="form-group">
              <label class="border border-secondary btn" onclick="addPertanyaan()">+ Tambah Pertanyaan
                <br>
              </label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
          </form>
        </div>
        <div class="col-md-1"></div>
      </div>
    </div>
  </div>
  <footer style="position: absolute;bottom: 0; width: 100%;height: 60px;line-height: 60px;" class="bg-dark">
    <div class="container text-center">
      &copy;BMNC - Kelompok 8 Kelas A
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  function addPertanyaan() {
    console.log("test");
    $("#pertanyaan").append("<div class=\"form-group\">\n<label>Pertanyaan Seputar Polling</label>\n<input type=\"text\" class=\"form-control\" placeholder=\"Masukan Pertanyaan\"> </div>");
  }
</script>

</html>