app_login/urls.py
from .views import index, login, logout
from django.conf.urls import url

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login', login, name='login'),
    url(r'^logout', logout, name='logout'),
]

bmnc_news/urls.py
from django.views.generic import RedirectView
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
import app_login.urls as login
import app_registrasi.urls as registrasi
from django.urls import path, include
from app_polling import views as views_polling


urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('app_profile.urls')),
    path('berita/', include('app_berita.urls')),
    path('polling/', views_polling.index),
    path('buat-berita/', include('app_buat_berita.urls', namespace='app_buat_berita')),
    path('buat-polling-berita/', include('app_buat_polling_berita.urls', namespace='app_buat_polling_berita')),
    path('buat-polling-biasa/', include('app_buat_polling_biasa.urls', namespace='app_buat_polling_biasa')),
    url(r'^login/', include(('app_login.urls','login'), namespace='login')),
    url(r'^registrasi/', include(('app_registrasi.urls','registrasi'), namespace='registrasi')),
    url(r'^$', RedirectView.as_view(url='/login/', permanent=True), name='index'),
]

app_login/models.py
from django.db import models

# Create your models here.

app_login/views.py
from django.shortcuts import render

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from app_database.models import Users

response = {}

# Create your views here.

def index(request):
    content = {}
    if 'username' in request.session:
        idnarasumber = Users.objects.raw("SELECT * FROM USERS WHERE username='%s'" % request.session.get('username'))[0].id_narasumber.id
        return HttpResponseRedirect('../profile/' + str(idnarasumber))
    elif 'invalid' in request.session:
        content['alert']=request.session['invalid']
        del request.session['invalid']
    else:
        content['alert']=''
    return render(request, 'app_login/login.html', content)

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        narasumber = Users.objects.raw('SELECT * FROM Users WHERE username = %s', [username])

        if (username == '' or password == ''):
            request.session['invalid'] = 'Lengkapi Informasi Login'
        elif not narasumber:
            request.session['invalid'] = 'Informasi Login Tidak Valid'
        else:
            try :
                if(narasumber[0].password!=password):
                    request.session['invalid'] = 'Informasi Login Tidak Valid'
                else :
                    request.session['username'] = username
                    id = narasumber[0].id_narasumber
                    request.session['id_narasumber'] = id.id
            except IndexError:
                request.session['invalid'] = 'Username Tidak Terdaftar'
    return HttpResponseRedirect(reverse('login:index'))

def logout(request):
    if 'username' in request.session:
        request.session.flush()
    return HttpResponseRedirect(reverse('login:index'))

app_login/templates/app_login/dashboard.html
<html>
<head>
	<title> Dashboard </title>
</head>
<body>
	<h2> {{ message }} </h2>
	<a href="{% url 'login:logout' %}" class="btn info" style="color:RoyalBlue">Logout</a>
</body>
</html>

app_login/templates/app_login/login.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="../static/css/now-ui-kit.css"> 
  <title> Login </title>
  
  </head>

<body class="bg-light">
  <nav class="navbar navbar-expand-md bg-primary navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="#">
        <i class="fa d-inline fa-lg fa-cloud"></i> Biru Merah News Company</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </nav>
  <div class="py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-5 offset-md-4">
          <h2>
            <center>Login User</center>
          </h2>
          <br>
          <form class="" action="{% url 'login:login' %}" method="POST">
			{% csrf_token %}
            <div class="form-group">
              <label>Username</label>
              <input type="text" name="username" class="form-control" placeholder="Enter Username"> </div>
            <div class="form-group">
              <label>Password</label>
              <input type="password" name="password" class="form-control" placeholder="Enter Password"> </div>
			  <font color = "red">
			  <span id = "pw_alert"> {{alert}} </span>
			  </font>
            <br>
            <center>
              <button onclick="myFunction()" type="submit" class="btn btn-primary" value="Login">Login</button>
			  <a class="btn btn-primary" href= "{% url 'registrasi:index' %}"> Tidak Punya Akun? Registrasi dulu </a>
            </center>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <div class="text-white bg-dark" style="bottom:0px">
    <div class="row">
      <div class="col-md-12 mt-3">
        <p class="text-center">©BMNC Kelompok 8 Kelas A</p>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <script src = "{% static 'js/login.js' %}" </script>
</body>

</html>